### ISSUE TITLE
Add support for dryContact sensor

### ISSUE THREAD

**Issue by macjeff** [Einstein42/udi-ecobee-poly#64] opened 2020-12-10 02:27 UTC
It may be there server as I have another app that was authorized with them and now not authorized and it wont re-authorize but my ISY shows lots of errors in the logs which I attached.  

Any idea why its not working.  I have not changed anything and it was working.

[Ecobee_logs_2020-12-9_212339.zip](https://github.com/Einstein42/udi-ecobee-poly/files/5669901/Ecobee_logs_2020-12-9_212339.zip)

**Comment by jimboca** [comment] 2020-12-25 01:59
The node server currently on supports thermostat's and remote thermostat sensors, first time I've seen dryContact

`2020-12-09 15:10:16,976 Controller polyinterface      ERROR    node_types:getSensorAddress: t170767287984:getSensorAddress: Unable to determine sensor address for: {'id': 'ei:0:1', 'name': '', 'type': 'monitor_sensor', 'inUse': False, 'capability': [{'id': '', 'type': 'dryContact', 'value': '0'}]}
`

**Comment by macjeff** [comment] 2020-12-25 02:12
My ecobee system has the following

  Ecobee 3 with Humidifier Connection (acts as humidistat to Aprilaire)
          Multiple Gen 1 sensors and 1 Gen 2 sensor
  Ecobee 4
         Multiple Gen 1 sensors and 1 Gen 2 sensor

It could only be the gen 2 sensor or the humidistat on there.

**Comment by jimboca** [comment] 2020-12-25 03:11
Ok, must be the controller for the humidistat? Can you try and research to see what it is?

**Comment by macjeff** [comment] 2020-12-25 04:28
The controller is built into every ecobee.  It’s just two wires to the humidifier which turns it on an off based on humidity.   It works with any humidifier.

**Comment by jimboca** [comment] 2020-12-25 18:27
Duplicate of #24

**Closed as completed by jimboca** 2020-12-25 18:27 UTC
Labels: duplicate, enhancement

**Comment by jimboca** [comment] 2020-12-25 19:17
Please see #24 and comment there after I release 2.2.0
